import Head from "next/head";
import Layout from "@/features/jobs/Layout";
import Loading from "@/components/Loading";
import { loadingAtom } from "@/atoms/atoms";
import { Typography } from "@mui/material";
import { useEffect, useState } from "react";
import { useAtom } from "jotai";
import JobList from "@/features/jobs/JobList";
import fetch from "@/libs/fetch";
import { JobListResponse, JobType } from "@/features/jobs/job.type";

export default function Bookmark() {
  const [isLoading, setLoading] = useAtom(loadingAtom);
  const [bookmarkList, setBookMarkList] = useState<JobType[]>([]);

  useEffect(() => {
    (async () => {
      setLoading(true);
      const { data } = await fetch.get<JobListResponse>(
        "/api/v1/jobBookmarkList"
      );
      setBookMarkList(data.jobList);
    })().finally(() => {
      setLoading(false);
    });
  }, [setLoading]);

  return (
    <>
      <Head>
        <title>エンジニア求人サイト | ブックマーク一覧</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <Layout>
          <Typography fontSize={24} pb={2} fontWeight={500} variant="h2">
            ブックマーク一覧
          </Typography>
          {!isLoading ? (
            <JobList jobList={bookmarkList} showBookmark={false} />
          ) : null}
        </Layout>
      </div>
      <Loading open={isLoading} />
    </>
  );
}
