import Head from "next/head";
import Layout from "@/features/jobs/Layout";
import Loading from "@/components/Loading";
import {
  jobBookmarkAtom,
  jobBookmarkIdsAtom,
  loadingAtom,
} from "@/atoms/atoms";
import { Box, Typography } from "@mui/material";
import { useEffect } from "react";
import { useAtom } from "jotai";
import JobList from "@/features/jobs/JobList";
import fetch from "@/libs/fetch";
import { JobListResponse } from "@/features/jobs/job.type";
import BasicPagination from "@/components/BasicPagination";
import { useRouter } from "next/router";
import LoadPage from "@/components/LoadPage";

export default function Bookmark() {
  const [isLoading, setLoading] = useAtom(loadingAtom);
  const [bookmarkIds, setBookMarkIds] = useAtom(jobBookmarkIdsAtom);
  const initialState: JobListResponse = {
    jobList: [],
    meta: {
      per_page: 0,
      current_page: 0,
      total: 0,
      from: 0,
      to: 0,
    },
  };
  const [bookmark, setBookMark] = useAtom(jobBookmarkAtom);
  const router = useRouter();

  const handleChangePagination = async (
    _: React.ChangeEvent<unknown>,
    value: number
  ) => {
    try {
      setLoading(true);
      const { data } = await fetch.get<JobListResponse>(
        `/api/v1/jobBookmarkList?page=${value}`
      );
      setBookMark(data);
      router.push(`/job/bookmark?page=${value}`, undefined, {
        shallow: true,
      });
    } catch (error) {
      console.error(error);
    } finally {
      setLoading(false);
      window.scrollTo({ top: 0 });
    }
  };

  useEffect(() => {
    (async () => {
      setLoading(true);
      const { data } = await fetch.get<JobListResponse>(
        "/api/v1/jobBookmarkList"
      );
      const { data: bookmarkIds } = await fetch.get<number[]>(
        `/api/v1/jobBookmarkIds`
      );
      setBookMark(data);
      setBookMarkIds(Object.values(bookmarkIds));
    })().finally(() => {
      setLoading(false);
    });
  }, [setLoading, setBookMarkIds, setBookMark]);

  return (
    <>
      <Head>
        <title>エンジニア求人サイト | ブックマークした求人</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <Layout>
          <Typography fontSize={24} pb={2} fontWeight={500} variant="h2">
            ブックマークした求人
          </Typography>
          {!isLoading && bookmark && bookmark.meta.total ? (
            <>
              <JobList
                jobList={bookmark.jobList}
                showBookmark={false}
                showDeleteBookmark
              />
              <Box pt={2} pb={8}>
                <BasicPagination
                  jobData={bookmark}
                  handleChange={handleChangePagination}
                />
              </Box>
            </>
          ) : (
            <LoadPage />
          )}
        </Layout>
      </div>
      <Loading open={isLoading} />
    </>
  );
}
