import Head from "next/head";
import Layout from "@/features/jobs/Layout";
import Loading from "@/components/Loading";
import { loadingAtom } from "@/atoms/atoms";
import { useAtomValue } from "jotai";
import BookmarkContent from "@/features/jobs/bookmark/BookmarkContent";

export default function Bookmark() {
  const isLoading = useAtomValue(loadingAtom);

  return (
    <>
      <Head>
        <title>エンジニア求人サイト | ブックマークした求人</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <Layout>
          <BookmarkContent />
        </Layout>
      </div>
      <Loading open={isLoading} />
    </>
  );
}
