import Head from "next/head";
import { GetServerSideProps } from "next";
import { useEffect } from "react";
import Loading from "@/components/Loading";
import { useAtom, useSetAtom } from "jotai";
import { jobBookmarkIdsAtom, jobDetailAtom, loadingAtom } from "@/atoms/atoms";
import DetailContentsWrap from "@/features/jobs/detail/DetailContentsWrap";
import { useRouter } from "next/router";
import { init } from "@/features/jobs/detail/init";

export default function Detail({ id }: { id: string }) {
  const [isLoading, setIsLoading] = useAtom(loadingAtom);
  const setBookmarkIds = useSetAtom(jobBookmarkIdsAtom);
  const setDetail = useSetAtom(jobDetailAtom);
  const router = useRouter();
  useEffect(() => {
    (async () => {
      setIsLoading(true);
      const result = await init(id);
      if (!result) {
        throw new Error("データの取得に失敗しました。");
      }
      const { job, bookmarkIds } = result;
      setDetail(job);
      setBookmarkIds(Object.values(bookmarkIds));
    })()
      .then(() => {
        setIsLoading(false);
      })
      .catch(() => {
        setIsLoading(false);
        router.replace("/404.html");
      });
  }, [id, setDetail, setBookmarkIds, setIsLoading, router]);
  return (
    <>
      <Head>
        <title>エンジニア求人サイト</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <DetailContentsWrap />
      <Loading open={isLoading} />
    </>
  );
}

/**
 * getServerSideProps
 */
export const getServerSideProps: GetServerSideProps = async ({ query }) => {
  if (typeof query?.id !== "string" || !query.id) {
    return {
      notFound: true,
    };
  }
  return {
    props: {
      id: query.id,
    },
  };
};
